/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_audiorecordertest_E2E */

#ifndef _Included_com_example_audiorecordertest_E2E
#define _Included_com_example_audiorecordertest_E2E
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_audiorecordertest_E2E
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_audiorecordertest_E2E_init
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_audiorecordertest_E2E
 * Method:    recognize
 * Signature: ([S)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_audiorecordertest_E2E_recognize
  (JNIEnv *, jobject, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
